import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LayoutWithTerminal from "@/components/Layout/LayoutWithTerminal";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "Rifki N D",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          jetBrainsMono.className,
          "antialiased h-full bg-neutral-900 overflow-hidden"
        )}
      >
        {/* Desktop View */}
        <div className="hidden md:flex min-h-screen w-full items-center justify-center">
          <div className="relative flex flex-col w-[90vw] max-w-[1600px] h-[90vh] max-h-screen bg-neutral-950 rounded-2xl shadow-2xl border border-neutral-800 overflow-hidden">
            <LayoutWithTerminal>
              <div className="flex-1" style={{ overflow: 'hidden' }}>
                {children}
              </div>
            </LayoutWithTerminal>
          </div>
        </div>

        {/* Mobile View */}
        <div className="flex items-center justify-center h-full md:hidden">
          <p className="text-xl font-semibold text-center">
            📱 Sorry! The mobile version is coming soon... 🚀 &apos; Stay Tune
            &apos;
          </p>
        </div>
      </body>
    </html>
  );
}
