import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "Rifki N D",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          jetBrainsMono.className,
          "antialiased h-full overflow-hidden"
        )}
      >
        {/* Desktop View */}
        <div className="hidden md:block h-full">{children}</div>

        {/* Mobile View */}
        <div className="flex items-center justify-center h-full md:hidden">
          <p className="text-xl font-semibold text-center">
            📱 Sorry! The mobile version is coming soon... 🚀
            &apos; Stay Tune &apos;
          </p>
        </div>
      </body>
    </html>
  );
}
